apiVersion: v1
kind: Service
metadata:
  name: website-backend-service
spec:
  type: NodePort
  selector:
    app: website-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
